### ISSUE TITLE
Help setting up a manual experiment

### ISSUE THREAD

**Issue by polyfractal** [usnistgov/optbayesexpt#5]
Hi there! I was recently directed towards this package, and it looks really lovely! I'm hoping to use it to help optimize a micromachining/drilling application, drilling small holes in glass. The parameter space to explore is pretty large, and the cost to evaluate each sample is very high (set up the toolpath manually, run the CNC machine, photograph the results and quantify the hole quality in ImageJ). I was hoping to use this package to help explore the parameter space a bit more intelligently than the usual brute-forcing method 😁

I've attempted to modify the "server" demo but think I'm fundamentally misunderstanding how the evaluation model and settings/parameters interact.  

There are three experimental settings to adjust: spindle RPM, how quickly the machine moves (feed rate) and a "pecking" depth when drilling
```py
# RPM 10,000 - 30,000
rpms = np.linspace(10000, 30000, 100)

# feed rates 0.01 - 1.0 inches/s
feedrates = np.linspace(0.01, 1.0, 100)

# pecking depth 0 - 0.002"
pecking = np.linspace(0, 0.002, 100)
```

There are two parameters which are recorded from each test: the "chipout" area around each hole, and the material removal rate (MRR). From the docs, it seems I should set the prior's according to the expected distribution of values:
```py
# Generate a *prior* distribution of parameters
n_samples = 1000

#chipout area ~100k - 400k pixels
chipoutVals = np.random.uniform(100000, 400000, n_samples)

# mrr ~0-100 mm^3/s
mrrVals = np.random.uniform(0, 100, n_samples)


settings = (rpms, feedrates, pecking,)
parameters = (chipoutVals, mrrVals, )
constants = ()
```

The goal is to minimize chipout area and maximize MRR. The minimum hole size with no chipout is ~100k pixels, so I combine the two in a fairly crude fashion as a first test:

```py
def drilling_model(settings, parameters, constants):
    rpm, feedrate, pecking, = settings
    chipout, mrr = parameters

    # some debug to see what's going on
    print("settings", rpm, feedrate, pecking)
    print("parameters", chipout, mrr)

    chipout = min(100000, chipout)
    return ((100000/chipout)*50) + mrr
```

And then over in the client, we ask for a new setting, have the user enter the measured chipout area and MRR and send back to the server:

```py
    # get a new recommended setting
    f_setting = tcpcmd({'command': 'goodset', 'pickiness': 6})
    print(f_setting)

    print("Enter Chipout Area:")
    chipout = input()

    print("Enter MRR:")
    mrr = input()

    # report measurement results to the OBE_Server
    tcpcmd({'command': 'newdat', 'x': (f_setting[0], f_setting[1], f_setting[2]), 'y': (chipout, mrr), 's':0.005})
```

At least in theory 🙂 The server errors out because it appears the parameters provided to the evaluation function are actually the priors that I defined earlier, instead of the chipout/mrr variables the client is sending in `y`? I might just have a syntax issue, but I suspect I'm actually misunderstanding a critical part of how this is all supposed to work. I tweaked things for a while and have re-read the docs, but afraid I haven't figured out what I'm doing wrong.

Any help would be greatly appreciated!  Thanks!  Attached are the full client/server files in case that's easier to see what I'm doing/doing wrong :)

[server.zip](https://github.com/usnistgov/optbayesexpt/files/10338989/server.zip)

**Comment by rmcmichael-nist** [comment]
Hi Polyfractal,

Thanks for your question and for all the details.  It looks like an interesting problem. I think the root of the difficulty might be that you are working on an optimization/minimization problem and optbayesexpt isn't really designed for that.   I see things start to go awry when MRR and chipout are packaged as parameters. MRR and chipout look like measurement data to me, and drilling model appears to compute a figure of merit.

Optbayesexpt is designed for estimating parameters of a model, like least-squares fitting finds "best" values for parameters of a fit function.  For example, if there were a reliable model that predicted measured values y = (MRR, chipout) or the figure of merit as a function of settings = (rpm, pecking, feedrate), that model would probably also have some parameters in it, say parameters = (a, b, c) related to glass properties, bit properties etc.   Optbayesexpt is designed to help you find values for parameters (a, b, c) efficiently.  If a dependable parametric model isn't available, optbayesexpt probably isn't the right tool.

For your work, I'd suggest looking into Bayesian Optimization.  Just based on some introductory material I've read, it's a method for optimizing when you don't know much about an underlying model. It usually involves Gaussian processes. 

I hope this helps,
Bob

**Comment by polyfractal** [comment]
Hiya Bob, thanks for the quick response! Your explanation makes sense, it definitely seems like I was misinterpreting the intent of the package.

In theory the figure of merit is a function of the settings (glass properties, bit properties, feed-per-tooth, etc) because glass will move from a brittle fracture regime to ductile-cutting under the right conditions, which directly affects things like chipout at the top surface.  But it's probably too far removed and as you said not a good fit

I'll do some reading on Bayesian Optimization! Cheers for the advice and the Optbayesexpt, seems like a lovely package to work with if I actually had a problem it was suited for 😊
